services:
  database:
    image: mariadb:10.6
    container_name: xlp_mariadb
    restart: always
    command: --lower-case-table-names=1 --transaction-isolation=READ-COMMITTED --log-bin=ROW --server-id=1 --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mountpoint/mariadb:/var/lib/mysql
      - ./mountpoint/backup_restore/mariadb:/mnt/backup_restore/mariadb
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - mediawiki_network

  mediawiki:
    image: emhavis/pkc_semanticwiki:v1.37.1.build.2
    container_name: xlp_mediawiki
    restart: always
    ports:
      - ${PORT_NUMBER}:80
    volumes:
      - ./mountpoint/images:/var/www/html/images
      - ./mountpoint/backup_restore/mediawiki:/mnt/backup_restore/mediawiki
      - ./mountpoint/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./backup/xml:/var/www/html/backup
      - ./mountpoint/ansible:/mnt/ansible
    depends_on:
      - database
    networks:
      - mediawiki_network

networks:
  mediawiki_network:
    driver: bridge